# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/motorola/guamp/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/motorola/guamp

PRODUCT_COPY_FILES += \
    vendor/motorola/guamp/proprietary/lib/libbluetooth.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libbluetooth.so \
    vendor/motorola/guamp/proprietary/lib/libbluetooth_qti.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libbluetooth_qti.so
